### PR TITLE
add .uk and .co.uk domain expiry

### PR DESCRIPTION
**Pull request by BuildTheRobots**
add .co.uk and .uk domain expiry

### CODE REVIEW

**Comment by ewypych** [comment]
Hi @BuildTheRobots – thanks for your contribution! Could you please add the necessary changes to the README file as well? Thanks!

**Comment by BuildTheRobots** [comment]
Updated :)

**Comment by ewypych** [comment]
Thanks a lot! One more thing I didn't notice yet – you did that in an "old" way. I've added in #15 some additional steps for each domain (which for sure could be done better), that prevent some ugly output when the domain doesn't have an expiration date, or the domain is expired yet. 

Now `nominet.uk` check ends with:

```
$ ./check_domain_expiration.sh -d nominet.uk
date: invalid date '+%Y-%m-%d'
date: invalid date '+%s'
CRITICAL - domain has expired!
```

because of the lack of expiration date in the WHOIS response. Please see `.shop` for reference:

```
        elif [ "$DTYPE" == "shop" ]
        then
		EXDATE=$(${WHOIS} -h whois.nic.shop "${1}" | ${AWK} '/Registry Expiry Date:/ { gsub("[:.]","-"); print $4 }' | cut -d 'T' -f1)
		if [ -z "$EXDATE" ]
		then
			EXP_DAYS=NULL
		else
			EXP_DAYS=$(( ( $(date -ud ${EXDATE} +'%s') - $(date -ud `date +%Y-%m-%d` +'%s') )/60/60/24 ))
		fi
```

I see that `.im` domain was done in a wrong way, I'll fix that, but could you please also update your code to meet these requirements?

Also, I think that I need to find a better way how to avoid this problem – `if` in each domain is not the best solution... 😅

**Comment by BuildTheRobots** [comment]
I have fixed both im and uk/.co.uk

Please let me know if it's ok - and hope you're having a good week :)

**Comment by ewypych** [comment]
Looks and works (as far as I can see) fine, thanks! :) I'll make a new release in a few minutes, so your week probably would be much better than now! :D

**Pull request merged**
